generator:
  class: sfPropelGenerator
  param:
    model_class:           Video
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Video
    plural:                Videos
    route_prefix:          video
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   backend/empty.css

    config:
      actions: ~
      fields:
        id: { label: ID }
        is_published: { label: "Published?" }
      list:
        title: Videos
        display: [id, type, =title, length, is_published, published_at]
      filter:
        display: [title, type, is_published]
      form:    ~
      edit:    ~
      new:     ~
