all:
  components:
    sidebar: [_calendar, sidebar]
  stylesheets: [frontend/calendar.css]
  javascripts:
    - frontend/calendar/DateSelect.js
    - frontend/calendar/Dates.js
    - frontend/calendar/Checkboxes.js
