prod:
  domain_name: "collectorsquest.com"
  www_domain: "www.collectorsquest.com"
  static_domain: "static.collectorsquest.com"
  multimedia_domain: "multimedia.collectorsquest.com"
  shopify_domain_name: "collectorsquest.myshopify.com"
  admin_email_id: "no-reply@collectorsquest.com"

  cq:
    www_domain: "http://www.collectorsquest.com/"
    static_domain: "http://static.collectorsquest.com/"
    multimedia_domain: "http://multimedia.collectorsquest.com"

  ice_assets:
    domain: "cqcdns.com"

  god_auth:
    secret: "s6nr1ea16fo1br0wn5a31wnzhhazerr8"
    timeout:  3600

  paypal:
    api_username: "dvds_api1.collectorsquest.com"
    api_password: "7XDP2KD5WPTZMRLX"
    api_signature: "AFcWxV21C7fd0v3bYYYRCpSSRl31A6NhuD4EARHUuWnwb9OPdCGC8x8U"

    api_url: "https://api-3t.paypal.com/nvp"
    is_online: true

    payment_action: "Sale"
    currency_code: "USD"
    payment_method: "doDirectPayment"

    url: "https://www.paypal.com/cgi-bin/webscr"
    merchant_account: "custserv@collectorsquest.com"

  credentials:
    amazon: "0Q4JCH5ZFJ3WBVP7N9R2"
    yahoo: "hbaTeUTV34GucRooge4L.uEQiK_wcbb2eMx6yUWAEUoQrdOPCIdj_2yTAbvt1QVryEc8WFUbu00X4hyEbUKLwg--"
    akismet: "8fd3f2fddbaa"
    google_maps: "ABQIAAAAFWhrOd_LZ8oN4w-vkUWughQAU-WnqYQCO7zppSGvHR51tCrN4xRY0TaQWDhMG_uhoslQtMZplJu3gg"
    disqus_user_key: "rCJyPA1GJlX3hoF3tdSdrGbbeGBeI7I9G1Qspd5QuR6AiCscBxREmoo1SLBnlJyf"
    disqus_forum_key: "nqopSzGkkro8tc53AgA3DNW56WSYBbZRetdoNPE8whwKY7b7dvELc05Nm9Yq5nMD"
    impermium: "6eed575e07cc2431293287a570d0afd0c3efde87"
    defensio: "B7107AA9A90675C6072F5D788FF21D94"
    dlvrit: "2d8ba224796541ff8c87659ee82fda93"

    rpxnow:
      application_domain: "https://collectorsquest.rpxnow.com/"
      application_id: "ecaoeilckeolccbmopdp"
      api_key: "e41ef45f2494b81cd32e6f2bbd34156f32be8012"

    recaptcha:
      public_key:  "6LdACwsAAAAAAE5tZTcYG47Lth2jzxxZeXAbll-Z"
      private_key: "6LdACwsAAAAAAM19l6G0lFk4F560SWvBM2k5M9L0"

    facebook:
      application_id: "12734695313"
      application_secret: "6f6c7cc89ddb21461821a84aa48f2b01"
