all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_com;host=cq-mysql-master
      username:   collectorsquest
      password:   rM6aKxoKKwUX4r
      persistent: true
      pooling:    true

  blog:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_blog;host=cq-mysql-master
      username:   collectorsquest
      password:   rM6aKxoKKwUX4r
      persistent: true
      pooling:    true

  calendar:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_calendar;host=cq-mysql-master
      username:   collectorsquest
      password:   rM6aKxoKKwUX4r
      persistent: true
      pooling:    true

stg:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=cq-mysql-master
      username:   staging
      password:   24QU2FJGLmA9vf

  blog:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=cq-mysql-master
      username:   staging
      password:   24QU2FJGLmA9vf

  calendar:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=cq-mysql-master
      username:   staging
      password:   24QU2FJGLmA9vf

  queue:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=cq-mysql-master
      username:   staging
      password:   24QU2FJGLmA9vf
