all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_com;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   collectorsquest
      password:   "TYN9KJ76gpy7fq"
      encoding:   utf8
      persistent: true
      pooling:    true

  blog:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_blog;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   collectorsquest
      password:   "TYN9KJ76gpy7fq"
      encoding:   utf8

  calendar:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_calendar;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   collectorsquest
      password:   "TYN9KJ76gpy7fq"

  queue:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_queue;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   collectorsquest
      password:   "TYN9KJ76gpy7fq"
      encoding:   utf8

  icepique:
      class:        sfPropelDatabase
      param:
        classname:  PropelPDO
        dsn:        mysql:dbname=collectorsquest_com;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
        username:   collectorsquest
        password:   "TYN9KJ76gpy7fq"
        encoding:   utf8


stg:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   staging
      password:   "KC93pNXux7x4FP"
      encoding:   utf8
      persistent: true
      pooling:    true

  blog:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   staging
      password:   "KC93pNXux7x4FP"
      encoding:   utf8

  calendar:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   staging
      password:   "KC93pNXux7x4FP"
      encoding:   utf8

  queue:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   staging
      password:   "KC93pNXux7x4FP"
      encoding:   utf8

  icepique:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   staging
      password:   "KC93pNXux7x4FP"
      encoding:   utf8


test:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_test;host=127.0.0.1
      username:   test
      password:   r4BBPRyt628YDF

  blog:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_test;host=127.0.0.1
      username:   test
      password:   r4BBPRyt628YDF
