all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_com;host=cq-mysql-master
      username:  collectorsquest
      password:  rM6aKxoKKwUX4r
      encoding:   utf8
      persistent: true
      pooling:    true

  blog:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_blog;host=cq-mysql-master
      username:  collectorsquest
      password:  rM6aKxoKKwUX4r
      encoding:   utf8
      persistent: true
      pooling:    true

  calendar:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_calendar;host=cq-mysql-master
      username:  collectorsquest
      password:  rM6aKxoKKwUX4r
      encoding:   utf8
      persistent: true
      pooling:    true

stg:
  propel:
    param:
      username:  staging
      password:  24QU2FJGLmA9vf

  blog:
    param:
      username:  staging
      password:  24QU2FJGLmA9vf

  calendar:
    param:
      username:  staging
      password:  24QU2FJGLmA9vf

  queue:
    param:
      username:  staging
      password:  24QU2FJGLmA9vf
