all:
  domain_name: "http://www.collectorsquest.com/"
  www_domain: "http://www.collectorsquest.com/"
  static_domain: "http://static.collectorsquest.com/"
  static_domain_name: "http://www.collectorsquest.com/"
  multimedia_domain: "http://multimedia.collectorsquest.com"
  shopify_domain_name: "collectorsquest.myshopify.com"
  admin_email_id: no-reply@collectorsquest.com

  paypal:
    api_username: "dvds_api1.collectorsquest.com"
    api_password: ""
    api_signature: ""
    api_url: "https://api-3t.paypal.com/nvp"
    is_online: true
    payment_method: doDirectPayment
    payment_action: Sale
    currency_code: USD

    url: "https://www.paypal.com/cgi-bin/webscr"
    merchant_account: "myackanich@collectorsquest.com"

    currency: USD
    #URL as module/action
    return_url: seller/updateOrder
    cancel_url: seller/becomeSeller
    notify_url: seller/callbackIPN

  cq:
    www_domain: "http://www.collectorsquest.com/"
    static_domain: "http://static.collectorsquest.com/"
    multimedia_domain: "http://multimedia.collectorsquest.com"

  api:
    amazon: ""
    yahoo: ""
    akismet: ""
    google_maps: ""
    disqus_user_key: ""
    disqus_forum_key: ""
    recaptcha:
      public_key: ""
      private_key: ""

  ice_libs:
    emails:
      sender: 'no-reply@collectorsquest.com'
      notify: 'developers@collectorsquest.com'

stg:
  www_domain: "http://www.collectorsquest.stg"
  static_domain: "http://static.collectorsquest.stg"
  multimedia_domain: "http://multimedia.collectorsquest.stg"

  cq:
    www_domain: "http://www.collectorsquest.stg"
    static_domain: "http://static.collectorsquest.stg"
    multimedia_domain: "http://multimedia.collectorsquest.stg"

  paypal:
    ## Setting for Pay Via PayPal Pro SANDBOX Account.
    api_username: ""
    api_password: ""
    api_signature: ""
    api_url: https://api-3t.sandbox.paypal.com/nvp
    is_online: false

    payment_action: Sale
    currency_code: USD
    payment_method: doDirectPayment

    ## Setting for Pay Via PayPal Pro SANDBOX Account.
    url: https://www.sandbox.paypal.com/cgi-bin/webscr
    merchant_account: prakash.virtueinfo_1302763980_biz@gmail.com

    currency: USD
    return_url: http://www.collectorsquest.stg/collector/updateOrder
    cancel_url: http://www.collectorsquest.stg/collector/becomeSeller
    notify_url: http://www.collectorsquest.stg/collector/callbackIPN

dev:
  www_domain: "http://www.collectorsquest.dev/"
  static_domain: "http://static.collectorsquest.dev/"
  multimedia_domain: "http://multimedia.collectorsquest.dev"

  cq:
    www_domain: "http://www.collectorsquest.dev/"
    static_domain: "http://static.collectorsquest.dev/"
    multimedia_domain: "http://multimedia.collectorsquest.dev"

  paypal:
    api_username: zecho2_1307375459_biz_api1.mail.bg
    api_password: 1307375482
    api_signature: ARGZylcXa9FrdnmIO0iUQs0rR92RAgDpfU7OiYGf5M34hnxegFkGwxD8
    api_url: https://api-3t.sandbox.paypal.com/nvp
    is_online: false

    payment_action: Sale
    currency_code: USD
    payment_method: doDirectPayment

    url: https://www.sandbox.paypal.com/cgi-bin/webscr
    merchant_account: zecho2_1260266487_biz@mail.bg
