all:
  shopify_domain_name: "collectorsquest.myshopify.com"
  admin_email_id: "no-reply@collectorsquest.com"

  ice_libs:
    emails:
      sender: 'no-reply@collectorsquest.com'
      notify: 'developers@collectorsquest.com'

  god_auth:
    secret: "s6nr1ea16fo1br0wn5a31wnzhhazerr8"
    timeout:  3600

  credentials:
    akismet: "8fd3f2fddbaa"
    google_maps: "ABQIAAAAFWhrOd_LZ8oN4w-vkUWughQAU-WnqYQCO7zppSGvHR51tCrN4xRY0TaQWDhMG_uhoslQtMZplJu3gg"
    disqus_user_key: "rCJyPA1GJlX3hoF3tdSdrGbbeGBeI7I9G1Qspd5QuR6AiCscBxREmoo1SLBnlJyf"
    disqus_forum_key: "nqopSzGkkro8tc53AgA3DNW56WSYBbZRetdoNPE8whwKY7b7dvELc05Nm9Yq5nMD"
    impermium: "6eed575e07cc2431293287a570d0afd0c3efde87"
    defensio: "BB85A65A8118C50AA3918CB254A34176"

    recaptcha:
      public_key: "6LdACwsAAAAAAE5tZTcYG47Lth2jzxxZeXAbll-Z"
      private_key: "6LdACwsAAAAAAM19l6G0lFk4F560SWvBM2k5M9L0"

    facebook:
      app_id: "293221397397430"
      app_secret: "21b6fb4368bbe3bf4157afe83e6945d4"

  paypal:
    api_username: ""
    api_password: ""
    api_signature: ""
    api_url: "https://api-3t.sandbox.paypal.com/nvp"
    is_online: false

    payment_action: "Sale"
    currency_code: "USD"
    payment_method: "doDirectPayment"

    url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
    merchant_account: ""

dev:
  domain_name: "collectorsquest.dev"
  www_domain: "www.collectorsquest.dev"
  static_domain: "static.collectorsquest.dev"
  multimedia_domain: "multimedia.collectorsquest.dev"

  cq:
    www_domain: "http://www.collectorsquest.dev/"
    static_domain: "http://static.collectorsquest.dev/"
    multimedia_domain: "http://multimedia.collectorsquest.dev"

  ice_assets:
    domain: "cqcdns.dev"

stg:
  domain_name: "collectorsquest.stg"
  www_domain: "www.collectorsquest.stg"
  static_domain: "static.collectorsquest.stg"
  multimedia_domain: "multimedia.collectorsquest.stg"

  cq:
    www_domain: "http://www.collectorsquest.stg"
    static_domain: "http://static.collectorsquest.stg"
    multimedia_domain: "http://multimedia.collectorsquest.stg"

  ice_assets:
    domain: "cqcdns.stg"
