all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_com;host=cq-mysql-master
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

  blog:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_blog;host=cq-mysql-master
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

  calendar:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_calendar;host=cq-mysql-master
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

  queue:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_queue;host=cq-mysql-master
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

  icepique:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_com;host=cq-mysql-master
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true


stg:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=cq-mysql-master

  blog:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=cq-mysql-master

  calendar:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=cq-mysql-master

  queue:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=cq-mysql-master

  icepique:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_stg;host=cq-mysql-master

dev:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=cq-mysql-master
      username:   root
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

      debug:
        realmemoryusage: true
        details:
          time:
            enabled: true
          slow:
            enabled: true
            threshold: 0.01
          memdelta:
            enabled: true
          mempeak:
            enabled: true
          method:
            enabled: true
          mem:
            enabled: true
          querycount:
            enabled: true

  blog:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=cq-mysql-master
      username:   root
      password:

  calendar:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=cq-mysql-master
      username:   root
      password:

  queue:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=cq-mysql-master
      username:   root
      password:

  icepique:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=cq-mysql-master
      username:   root
      password:


test:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_test;host=cq-mysql-master
      username:   root
      password:

  blog:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_test;host=cq-mysql-master
      username:   root
      password:
