all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_com;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

  blog:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_blog;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

  calendar:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_calendar;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

  queue:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_queue;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

  icepique:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=collectorsquest_com;host=master.cwvkronpbfrx.us-east-1.rds.amazonaws.com
      username:   collectorsquest
      password:
      encoding:   utf8
      persistent: true
      pooling:    true


dev:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=127.0.0.1
      username:   root
      password:
      encoding:   utf8
      persistent: true
      pooling:    true

      debug:
        realmemoryusage: true
        details:
          time:
            enabled: true
          slow:
            enabled: true
            threshold: 0.01
          memdelta:
            enabled: true
          mempeak:
            enabled: true
          method:
            enabled: true
          mem:
            enabled: true
          querycount:
            enabled: true

  blog:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=127.0.0.1
      username:   root
      password:

  calendar:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=127.0.0.1
      username:   root
      password:

  queue:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=127.0.0.1
      username:   root
      password:

  icepique:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_dev;host=127.0.0.1
      username:   root
      password:


test:
  propel:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_test;host=127.0.0.1
      username:   root
      password:

  blog:
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=collectorsquest_test;host=127.0.0.1
      username:   root
      password:

  icepique:
      param:
        classname:  DebugPDO
        dsn:        mysql:dbname=collectorsquest_test;host=127.0.0.1
        username:   root
        password:
