Vagrant::Config.run do |config|
  config.vm.box = "collectorsquest"
  config.vm.box_url = "http://collectorsquest.s3.amazonaws.com/virtualbox/collectorsquest-2011-12-01.box"

  # If you want to specify the host OS, create a file 'platform'
  # in the same directory as the .vagrant file.
  platform = (File.exists? 'platform') ? File.read('platform').strip : :detect

  if platform == 'windows'
    config.vm.forward_port("web", 80, 9458, :auto => true)
    config.vm.share_folder("collectorsquest", "/mnt/vhosts", "../../../", :nfs => false, :owner => "www-data", :group => "www-data")
    config.vm.share_folder("tmp", "/mnt/tmp", "c:/Windows/Temp", :nfs => false)
  elsif platform == 'darwin'
    config.vm.network "172.16.183.128"
    config.vm.share_folder("collectorsquest", "/mnt/vhosts", "../../../", :nfs => true)
    config.vm.share_folder("tmp", "/mnt/tmp", "/Volumes/Storage/tmp", :nfs => true)
  elsif platform == 'linux'
    config.vm.network "172.16.183.128"
    config.vm.share_folder("collectorsquest", "/mnt/vhosts", "../../../", :nfs => true)
    config.vm.share_folder("tmp", "/mnt/tmp", "/tmp", :nfs => true)
  else
    config.vm.network "172.16.183.128"
    config.vm.share_folder("collectorsquest", "/mnt/vhosts", "../../../", :nfs => true)
  end

  config.vm.customize do |vm|
    vm.name = "Collectors Quest"
    vm.memory_size = 2048
    vm.cpu_count = 2
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../cookbooks"

    chef.add_recipe("main")
    chef.add_recipe("main::subversion")
    chef.add_recipe("main::database")
    chef.add_recipe("main::web")
    chef.add_recipe("development")
  end

  config.package.name = "collectorsquest"
  # config.vm.boot_mode = :gui
end
