generator:
  class: sfPropelGenerator
  param:
    model_class:           PrivateMessage
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              PrivateMessage
    plural:                PrivateMessages
    route_prefix:          private_message
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   backend/empty.css

    config:
      actions: ~
      fields:  ~
      list:
        title: Messages
        display: [sender, receiver, subject, is_read, is_replied, is_deleted, created_at]
      filter:
        display: [subject, body]
      form:    ~
      edit:    ~
      new:     ~
