generator:
  class: sfPropelGenerator
  param:
    model_class:           CollectionCategory
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              CollectionCategory
    plural:                CollectionCategorys
    route_prefix:          collection_category
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   backend/empty.css

    config:
      actions: ~
      fields:
        id: { label: ID }
      list:
        title: Collection Categories
        display: [id, parent_id, name, tags_string, score]
      filter:
        display: [name]
      form:
        display: [parent_id, name, tags, score]
      edit:    ~
      new:     ~
