<?php


/**
 * This class adds structure of 'collection_item' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Oct 11 15:27:10 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CollectionItemMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CollectionItemMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(CollectionItemPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(CollectionItemPeer::TABLE_NAME);
		$tMap->setPhpName('CollectionItem');
		$tMap->setClassname('CollectionItem');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('COLLECTION_ID', 'CollectionId', 'INTEGER', 'collection', 'ID', false, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 50);

		$tMap->addColumn('SLUG', 'Slug', 'VARCHAR', false, 128);

		$tMap->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', true, null);

		$tMap->addColumn('EST_VALUE', 'EstValue', 'INTEGER', false, null);

		$tMap->addColumn('PURCHASED_PRICE', 'PurchasedPrice', 'INTEGER', false, null);

		$tMap->addColumn('CURRENCY', 'Currency', 'VARCHAR', false, 50);

		$tMap->addColumn('PHOTO', 'Photo', 'VARCHAR', false, 128);

		$tMap->addColumn('IS_FOR_SALE', 'IsForSale', 'BOOLEAN', false, null);

		$tMap->addColumn('NUM_VIEWS', 'NumViews', 'INTEGER', false, null);

		$tMap->addColumn('POSITION', 'Position', 'TINYINT', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // CollectionItemMapBuilder
